from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]


def load_module():
    module_path = REPO_ROOT / "installer" / "update_version.py"
    spec = importlib.util.spec_from_file_location("installer_update_version", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module from {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class UpdateVersionTest(unittest.TestCase):
    def setUp(self) -> None:
        self.module = load_module()
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
        self.workspace = Path(self.temp_dir.name)

    def test_resolve_versions_should_read_short_and_full_version(self) -> None:
        pubspec = self.workspace / "pubspec.yaml"
        pubspec.write_text('name: colmeia\nversion: 2.3.4+7\n', encoding="utf-8")
        self.module.PUBSPEC = pubspec

        short_version, full_version = self.module.resolve_versions()

        self.assertEqual("2.3.4", short_version)
        self.assertEqual("2.3.4+7", full_version)

    def test_update_setup_iss_should_replace_my_app_version(self) -> None:
        setup_iss = self.workspace / "setup.iss"
        setup_iss.write_text(
            '#define MyAppName "Colmeia"\n#define MyAppVersion "1.0.0"\n',
            encoding="utf-8-sig",
        )
        self.module.SETUP_ISS = setup_iss

        self.module.update_setup_iss("3.4.5")

        self.assertIn(
            '#define MyAppVersion "3.4.5"',
            setup_iss.read_text(encoding="utf-8-sig"),
        )

    def test_update_app_version_dart_should_write_generated_file(self) -> None:
        output = self.workspace / "lib" / "core" / "constants" / "app_version.g.dart"
        self.module.APP_VERSION_DART = output

        self.module.update_app_version_dart("9.8.7+6")

        self.assertEqual(
            "// Generated by installer/update_version.py - do not edit manually.\n"
            "const String appVersion = '9.8.7+6';\n",
            output.read_text(encoding="utf-8"),
        )


if __name__ == "__main__":
    unittest.main()
