import 'package:colmeia/features/sales/domain/entities/sales_live_map_point.dart';

class SalesLiveMapPointFactory {
  const SalesLiveMapPointFactory();

  SalesLiveMapPointSource createSource({
    required String id,
    required String name,
    required double salesAmount,
    required int salesCount,
    required String? uf,
    required String? city,
    required double? latitude,
    required double? longitude,
    required String? cep,
    required String? ibgeMunicipalityCode,
    required String? fantasyName,
    required String? branchName,
    required int? companyCode,
    required int? branchCode,
    required String? agentName,
    required bool salesDataLoading,
    required bool salesDataUnavailable,
    required String? salesDataStatusLabel,
    required String? subtitle,
    required Object? payload,
    bool preferCapitalFallback = false,
    bool allowUfFallback = true,
  }) {
    return SalesLiveMapPointSource(
      id: id,
      name: name,
      salesAmount: salesAmount,
      salesCount: salesCount,
      uf: uf,
      city: city,
      latitude: latitude,
      longitude: longitude,
      cep: cep,
      ibgeMunicipalityCode: ibgeMunicipalityCode,
      preferCapitalFallback: preferCapitalFallback,
      allowUfFallback: allowUfFallback,
      fantasyName: fantasyName,
      branchName: branchName,
      companyCode: companyCode,
      branchCode: branchCode,
      agentName: agentName,
      salesDataLoading: salesDataLoading,
      salesDataUnavailable: salesDataUnavailable,
      salesDataStatusLabel: salesDataStatusLabel,
      subtitle: subtitle,
      payload: payload,
    );
  }

  SalesLiveMapPoint createPoint({
    required String id,
    required String name,
    required String uf,
    required double latitude,
    required double longitude,
    required double salesAmount,
    required int salesCount,
    required String? fantasyName,
    required String? branchName,
    required int? companyCode,
    required int? branchCode,
    required String? agentName,
    required bool salesDataLoading,
    required bool salesDataUnavailable,
    required String? salesDataStatusLabel,
    required SalesLiveMapLocationResolution? locationResolution,
    required String? subtitle,
    required Object? payload,
    String? municipalityCode,
    String? city,
  }) {
    return SalesLiveMapPoint(
      id: id,
      name: name,
      uf: uf,
      latitude: latitude,
      longitude: longitude,
      salesAmount: salesAmount,
      salesCount: salesCount,
      municipalityCode: municipalityCode,
      city: city,
      fantasyName: fantasyName,
      branchName: branchName,
      companyCode: companyCode,
      branchCode: branchCode,
      agentName: agentName,
      salesDataLoading: salesDataLoading,
      salesDataUnavailable: salesDataUnavailable,
      salesDataStatusLabel: salesDataStatusLabel,
      locationResolution: locationResolution,
      subtitle: subtitle,
      payload: payload,
    );
  }

  SalesLiveMapPoint mergeAggregateOntoResolvedBase({
    required SalesLiveMapPoint base,
    required String name,
    required double salesAmount,
    required int salesCount,
    required String? fantasyName,
    required String? branchName,
    required int? companyCode,
    required int? branchCode,
    required String? agentName,
    required bool salesDataLoading,
    required bool salesDataUnavailable,
    required String? salesDataStatusLabel,
    required String? subtitle,
    required Object? payload,
  }) {
    return base.copyWith(
      name: name,
      salesAmount: salesAmount,
      salesCount: salesCount,
      fantasyName: fantasyName,
      branchName: branchName,
      companyCode: companyCode,
      branchCode: branchCode,
      agentName: agentName,
      salesDataLoading: salesDataLoading,
      salesDataUnavailable: salesDataUnavailable,
      salesDataStatusLabel: salesDataStatusLabel,
      subtitle: subtitle,
      payload: payload,
    );
  }
}
