enum AgentQueryKey {
  resumoParcelaFormaPagamento,
  resumoParcelaFormaPagamentoDiario,
  resumoParcelasDiaSemana,
  resumoParcelasDiaSemanaUsuario,
  resumoParcelasAnual,
  resumoParcelasFormaPagamentoPorMes,
  resumoParcelasMensal,
  resumoTotalDiarioVendas,
  resumoTotalVendasMunicipioFilialDiario,
  resumoVendasDiariasPorVendedor,
  resumoVendasDiariasOptsVendedor,
  resumoVendasDiariasOptsBairro,
  resumoVendasDiariasOptsMunicipio,
}
