#!/usr/bin/env python3
"""
Synchronize versioned Windows release files from pubspec.yaml.

Updates:
- installer/setup.iss -> MyAppVersion (short version)
- lib/core/constants/app_version.g.dart -> appVersion (full version)
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PUBSPEC = PROJECT_ROOT / "pubspec.yaml"
SETUP_ISS = PROJECT_ROOT / "installer" / "setup.iss"
APP_VERSION_DART = PROJECT_ROOT / "lib" / "core" / "constants" / "app_version.g.dart"


def main() -> None:
    short_version, full_version = resolve_versions()
    print(f"pubspec.yaml version: {full_version}")
    update_setup_iss(short_version)
    update_app_version_dart(full_version)
    print("Synchronization completed.")


def resolve_versions() -> tuple[str, str]:
    if not PUBSPEC.exists():
        raise SystemExit(f"pubspec.yaml not found: {PUBSPEC}")

    content = PUBSPEC.read_text(encoding="utf-8")
    match = re.search(
        r'^version:\s*["\']?(\d+\.\d+\.\d+(?:\+\d+)?)["\']?\s*(?:#|$)',
        content,
        re.MULTILINE,
    )
    if match is None:
        raise SystemExit("version was not found in pubspec.yaml")

    full_version = match.group(1).strip()
    short_version = full_version.split("+", maxsplit=1)[0]
    return short_version, full_version


def update_setup_iss(version: str) -> None:
    if not SETUP_ISS.exists():
        raise SystemExit(f"setup.iss not found: {SETUP_ISS}")

    content = SETUP_ISS.read_text(encoding="utf-8-sig")
    new_content, replacements = re.subn(
        r'#define MyAppVersion\s+".*"',
        f'#define MyAppVersion "{version}"',
        content,
    )
    if replacements != 1:
        raise SystemExit(
            "Expected exactly one MyAppVersion declaration in installer/setup.iss",
        )

    SETUP_ISS.write_text(new_content, encoding="utf-8-sig")
    print(f"  setup.iss: MyAppVersion = {version}")


def update_app_version_dart(full_version: str) -> None:
    content = (
        "// Generated by installer/update_version.py - do not edit manually.\n"
        f"const String appVersion = '{full_version}';\n"
    )
    APP_VERSION_DART.parent.mkdir(parents=True, exist_ok=True)
    APP_VERSION_DART.write_text(content, encoding="utf-8")
    print(f"  app_version.g.dart: appVersion = {full_version}")


if __name__ == "__main__":
    main()
